const $ = (s) => document.querySelector(s);
const timeline = $('#timeline');
const formatMs = (ms) => ms == null ? '-' : ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(1)}s`;
const apiHeaders = (json=false) => { const headers=json ? {'Content-Type':'application/json'} : {}; const key=$('#api-key').value; if(key) headers['X-API-Key']=key; return headers; };
const apiFetch = (url, options={}) => fetch(url,{...options,headers:{...apiHeaders(Boolean(options.body)),...(options.headers||{})}});
const eventUrl = (url) => { const key=$('#api-key').value; return key ? `${url}?api_key=${encodeURIComponent(key)}` : url; };
async function refreshHistory(){ const response=await apiFetch('/v1/research'); if(!response.ok){$('#history').textContent='작업 이력을 불러올 수 없습니다.';return;} const jobs=await response.json(); $('#history').innerHTML=jobs.map(job=>`<p><b>${job.status.toUpperCase()}</b> · ${job.topic}<br><small>${job.task_id} · ${job.metrics ? formatMs(job.metrics.duration_ms) : '진행 중'}</small></p>`).join('') || '아직 작업 이력이 없습니다.'; }
$('#research-form').addEventListener('submit', async (event) => { event.preventDefault(); timeline.innerHTML=''; $('#workspace').hidden=false; $('#report').textContent='조사 작업을 준비하고 있습니다.'; $('#exports').hidden=true; $('#retry').hidden=true; const body={topic:$('#topic').value,audience:$('#audience').value,depth:$('#depth').value}; const response=await apiFetch('/v1/research',{method:'POST',body:JSON.stringify(body)}); if(!response.ok){ $('#report').textContent='요청 실패: '+await response.text(); return; } const job=await response.json(); $('#task-id').textContent=job.task_id; $('#status').textContent=job.status.toUpperCase(); watch(job.task_id); });
function addEvent(event){ const row=document.createElement('li'); row.innerHTML=`<b>${event.phase}</b><span>${event.message}${event.details?.duration_ms ? ` · ${formatMs(event.details.duration_ms)}` : ''}</span>`; timeline.append(row); }
function showRetry(id){ $('#retry').hidden=false; $('#retry').onclick=async()=>{const response=await apiFetch(`/v1/research/${id}/retry`,{method:'POST'});if(response.ok){const job=await response.json();timeline.innerHTML='';$('#task-id').textContent=job.task_id;$('#status').textContent='QUEUED';watch(job.task_id);}}; }
function watch(id){ const stream=new EventSource(eventUrl(`/v1/research/${id}/events`)); stream.addEventListener('progress',(message)=>addEvent(JSON.parse(message.data))); stream.addEventListener('done',async()=>{stream.close(); const job=await (await apiFetch(`/v1/research/${id}`)).json(); $('#status').textContent=job.status.toUpperCase(); $('#report').textContent=job.report||job.error||'결과 없음'; if(job.status==='failed'){showRetry(id);refreshHistory();return;} if(job.status==='completed'){ const evaluation=await (await apiFetch(`/v1/research/${id}/evaluation`)).json(); $('#quality').innerHTML=`<strong>${evaluation.citation_score}/100</strong><p>유효 인용 ${evaluation.cited_references}개 / 수집 출처 ${evaluation.source_count}개</p><small>${evaluation.summary}</small>`; $('#performance').innerHTML=`<p><b>${formatMs(job.metrics?.duration_ms)}</b> · ${job.metrics?.provider || '-'} / ${job.metrics?.model || '-'}</p>`; const sources=await (await apiFetch(`/v1/research/${id}/sources`)).json(); $('#sources').innerHTML=sources.map(s=>`<p><b>[${s.source_number}]</b> <a href="${s.url}" target="_blank">${s.title}</a></p>`).join(''); const graph=await (await apiFetch(`/v1/research/${id}/graph`)).json(); $('#graph').innerHTML=`<p><b>${graph.sources.length}</b> source nodes · <b>${graph.relationships.length}</b> entity relations</p>`+graph.sources.map(s=>`<p><b>${s.source}</b><br><small>${s.entities.map(e=>e.name).filter(Boolean).join(' · ') || '연결된 엔터티 없음'}</small></p>`).join(''); $('#markdown').href=eventUrl(`/v1/research/${id}/export.md`); $('#pdf').href=eventUrl(`/v1/research/${id}/export.pdf`); $('#exports').hidden=false; refreshHistory(); }}); }
refreshHistory();
